/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.depoyonetim.arayuz;

import com.depoyonetim.islemler.*;
import javax.swing.JFrame;

/**
 *
 * @author ASUS
 */
public class KullaniciKayit extends javax.swing.JFrame {

    VeriTabaniBaglantisi veriTabaniBaglantisi = new VeriTabaniBaglantisi();
    VeriIslemleri veriIslemleri = new VeriIslemleri();

    /**
     * Creates new form KullaniciKayit
     */
    public KullaniciKayit() {
        initComponents();
        this.setLocation(veriIslemleri.StartScreenLocation(this.getBounds().getSize()));
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        authorizationRadioButtonGroup = new javax.swing.ButtonGroup();
        userNameText = new javax.swing.JLabel();
        userNameTextField = new javax.swing.JTextField();
        firsNameTextField = new javax.swing.JTextField();
        firstNameText = new javax.swing.JLabel();
        lastNameText = new javax.swing.JLabel();
        passwordText = new javax.swing.JLabel();
        passwordTextField = new javax.swing.JTextField();
        lastNameTextField = new javax.swing.JTextField();
        personelRadioButton = new javax.swing.JRadioButton();
        yoneticiRadioButton = new javax.swing.JRadioButton();
        saveBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        errorMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kullanıcı Kaydı");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        userNameText.setText("Kullanıcı Adı :");

        firstNameText.setText("İsim :");

        lastNameText.setText("Soyisim :");

        passwordText.setText("Parola :");

        authorizationRadioButtonGroup.add(personelRadioButton);
        personelRadioButton.setText("Personel");
        personelRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personelRadioButtonActionPerformed(evt);
            }
        });

        authorizationRadioButtonGroup.add(yoneticiRadioButton);
        yoneticiRadioButton.setText("Yönetici");

        saveBtn.setText("Kullanıcıyı Kaydet");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        cancelBtn.setText("Kaydı İptal Et");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        errorMessage.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        errorMessage.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(errorMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(firstNameText)
                            .addComponent(firsNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userNameText)
                            .addComponent(userNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(personelRadioButton, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(saveBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(yoneticiRadioButton)
                            .addComponent(lastNameText)
                            .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passwordText)
                            .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(errorMessage)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(passwordText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lastNameText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(userNameText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(userNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(firstNameText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(firsNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(personelRadioButton)
                    .addComponent(yoneticiRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBtn)
                    .addComponent(cancelBtn))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_formWindowClosing

    private void personelRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personelRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_personelRadioButtonActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        String dateString = veriIslemleri.dateString();
        int dateInteger = veriIslemleri.dateInteger();
        boolean personel = personelRadioButton.isSelected();
        boolean yonetici = yoneticiRadioButton.isSelected();
        String userName = userNameTextField.getText();
        String password = passwordTextField.getText();
        String firsName = firsNameTextField.getText();
        String lasName = lastNameTextField.getText();
        String authorization = "";
        if (userNameTextField.getText().trim().equals("") || passwordTextField.getText().trim().equals("") || firsNameTextField.getText().trim().equals("") || lastNameTextField.getText().trim().equals("")) {
            errorMessage.setText("Lütfen Tüm Alanları Doldurun");
            return;
        }
        if (personel) {
            authorization = "Personel";
        } else if (yonetici) {
            authorization = "Yönetici";
        } else {
            System.out.println("Lütfen Yetki Seçiniz");
            errorMessage.setText("Lütfen Yetki Seçin");
            return;
        }

        String sorgu = "INSERT INTO `users` (`Id`, `userName`, `password`, `firstName`, `lastName`, `authorization`, `date` , `dateCode`) VALUES (NULL, '" + userName + "', '" + password + "', '" + firsName + "', '" + lasName + "', '" + authorization + "', '" + dateString + "','" + dateInteger + "')";
        veriTabaniBaglantisi.ekle(sorgu);
        System.out.println(authorization + " Olarak Kaydedildi");
        errorMessage.setText(authorization + " Olarak Kaydedildi");
        userNameTextField.setText("");
        passwordTextField.setText("");
        firsNameTextField.setText("");
        lastNameTextField.setText("");


    }//GEN-LAST:event_saveBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        dispose(); // Bu fonksiyon pencereyi kapatır
    }//GEN-LAST:event_cancelBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KullaniciKayit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KullaniciKayit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KullaniciKayit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KullaniciKayit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KullaniciKayit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup authorizationRadioButtonGroup;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JLabel errorMessage;
    private javax.swing.JTextField firsNameTextField;
    private javax.swing.JLabel firstNameText;
    private javax.swing.JLabel lastNameText;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JLabel passwordText;
    private javax.swing.JTextField passwordTextField;
    private javax.swing.JRadioButton personelRadioButton;
    private javax.swing.JButton saveBtn;
    private javax.swing.JLabel userNameText;
    private javax.swing.JTextField userNameTextField;
    private javax.swing.JRadioButton yoneticiRadioButton;
    // End of variables declaration//GEN-END:variables
}
