/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.depoyonetim.arayuz;

import com.depoyonetim.islemler.*;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author ASUS
 */
public class KullaniciGirisi extends javax.swing.JFrame {

    VeriTabaniBaglantisi veriTabaniBaglantisi = new VeriTabaniBaglantisi(); //Veri Tabanı bağlantısı referansı oluşturuldu

    static String userNameTxt; // Diğer framelerde kullanabilmek için static değişken oluşturuldu
    private String passwordTxt; // sadece bu alan içerisinde kullanabileceğimiz özel static değiken oluşturuldu

    public String getUserNameTxt() { // Kullanıcı adını her dosyadan çekmemizi sağlar
        return userNameTxt;
    }

    public String getPasswordTxt() {//Parolayı her dosyadan çekmemizi sağlar
        return passwordTxt;
    }

    /**
     * Creates new form KullaniciGirisi
     */
    public KullaniciGirisi() { //Constructor alanı
        initComponents();
        this.setResizable(false);

        this.setLocation(StartScreenLocation(this.getBounds().getSize()));
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userNameText = new javax.swing.JLabel();
        passwordText = new javax.swing.JLabel();
        kullaniciAdiTxt = new javax.swing.JTextField();
        girisBtn = new javax.swing.JButton();
        parolaTxt = new javax.swing.JPasswordField();
        myErrorMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kullanıcı Girişi");
        setBounds(new java.awt.Rectangle(0, 0, 100, 100));
        setLocation(new java.awt.Point(0, 0));
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 238, 238));
        setMaximumSize(new java.awt.Dimension(295, 238));
        setMinimumSize(new java.awt.Dimension(295, 238));
        setSize(new java.awt.Dimension(295, 238));

        userNameText.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        userNameText.setText("Kullanıcı Adı :");

        passwordText.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        passwordText.setText("Parola :");

        kullaniciAdiTxt.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        kullaniciAdiTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kullaniciAdiTxtActionPerformed(evt);
            }
        });

        girisBtn.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        girisBtn.setText("Giriş Yap");
        girisBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                girisBtnActionPerformed(evt);
            }
        });

        parolaTxt.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        parolaTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parolaTxtActionPerformed(evt);
            }
        });

        myErrorMessage.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(passwordText)
                    .addComponent(userNameText)
                    .addComponent(kullaniciAdiTxt)
                    .addComponent(girisBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                    .addComponent(parolaTxt)
                    .addComponent(myErrorMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(userNameText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kullaniciAdiTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(passwordText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(parolaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(girisBtn)
                .addGap(18, 18, 18)
                .addComponent(myErrorMessage)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kullaniciAdiTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kullaniciAdiTxtActionPerformed
        //Kullanıcı adındayken entere basıp giriş yapmasını sağlayan alan
        singIn(); // Giriş methodu
    }//GEN-LAST:event_kullaniciAdiTxtActionPerformed

    private void girisBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_girisBtnActionPerformed
        //Giriş butonu ile giriş yapılmasını sağlayan alan
        singIn();//Giriş methodu
    }//GEN-LAST:event_girisBtnActionPerformed

    private void parolaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parolaTxtActionPerformed
        //Parola adındayken entere basıp giriş yapmasını sağlayan alan
        singIn(); //Giriş methodu
    }//GEN-LAST:event_parolaTxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public void singIn() {
        userNameTxt = kullaniciAdiTxt.getText();//userNameTxt değişkenine textboxtan alınan değer eşitlendi
        passwordTxt = String.valueOf(parolaTxt.getPassword());//passwordTxt,, textboxtan alınan değer eşitlendi

        if (userNameTxt.trim().equals("") || passwordTxt.trim().equals("")) {//gereksiz boşluklar silindikten sonra alanın boş mu dolu mu olduğunu kontrol eder
            myErrorMessage.setText("Lütfen Tüm Alanları Doldurun");//Eğer alan boşsa alanı doldur hatası verir

        } else {//Eğer alan dolysa bu blok çalışır
            String sorgu = "SELECT count(Id) as Id FROM `users` WHERE userName='" + userNameTxt + "' AND password='" + passwordTxt + "'";//MySql veri tabanına gödereceğimiz sorgudur
            ResultSet baglanti = veriTabaniBaglantisi.baglanti(sorgu);//Veri tabanı bağlantısı için hazırlamış oluduğumuz dosyadan verileri çekiyor ResultSet baglanti değişkenine atıyor

            try {
                while (baglanti.next()) { //ResultSet baglanti içerisinde okucanak değer varmı diye kontrol edip varsa döngüyü çalıştırıyor.
                    //Bu alan çalıştığında verler okunup eşitlenir
                    if (baglanti.getInt("Id") == 1) { // eğer bilgilerle eşleşen bir kayıt varsa giriş yapar
                        new DepoYonetim().setVisible(true); // setVisible dosyayı açmayı sağlar
                        setVisible(false);//Bu kod bloğu da içinde bulunduğumuz framei kapatır.
                        System.out.println("Bağlantı Başarılı");//Bağlantı başarılı olduğundabu satır çalışır ve konsola başarılı yazar

                    } else {//Kullanıcı adı veya parola hatalı ise bu kod bloğu çalışır
                        myErrorMessage.setText("Kullanıcı Adı veya Parola Hatalı");//Hata mesajı verir
                        System.out.println("Bağlantı Başarısız");//Bağlantı Başarısız olduğundabu satır çalışır ve konsola başarısız yazar
                    }

                }
            } catch (SQLException ex) {// SQL hatası yakar
                ex.printStackTrace();//hatanın ne olduğunu söyler
            }
        }
        
    }
    
    public Point StartScreenLocation(Dimension formSize) {
        Point p = new Point();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();

        double screenHeight = screenSize.getHeight();
        double screenWidth = screenSize.getWidth();
        double formHeight = formSize.getHeight();
        double formWidht = formSize.getWidth();

        int x = (int) screenHeight / 2 - (int) formHeight / 2;
        int y = (int) screenWidth / 2 - (int) formWidht / 2;
        p.setLocation(y, x);
        return p;
    }
    
    public static void main(String args[]) {//Bu blok frame'in kendi başına işlem yapması sağlar
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KullaniciGirisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KullaniciGirisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KullaniciGirisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KullaniciGirisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KullaniciGirisi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton girisBtn;
    private javax.swing.JTextField kullaniciAdiTxt;
    private javax.swing.JLabel myErrorMessage;
    private javax.swing.JPasswordField parolaTxt;
    private javax.swing.JLabel passwordText;
    private javax.swing.JLabel userNameText;
    // End of variables declaration//GEN-END:variables
}
