/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.depoyonetim.arayuz;

import com.depoyonetim.islemler.*;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class MusteriListele extends javax.swing.JFrame {

    VeriTabaniBaglantisi veriTabaniBaglantisi = new VeriTabaniBaglantisi();
    VeriIslemleri veriIslemleri = new VeriIslemleri();
    DefaultTableModel myModel = new DefaultTableModel();
    Object[] columns = {"Id", "TC/Vergi No", "İsim (Kişi/Şirket)", "Telefon", "Telefon (Yedek)", "Adres", "E-Mail", "Tarih"};
    Object[] rows = new Object[8];

    private String uniqueTextValue;
    private String nameTextValue;
    private String phoneTextValue;
    private String phone2TextValue;
    private String adressTextValue;
    private String emailTextValue;
    private String idNumberValue;

    public String getIdNumberValue() {
        return idNumberValue;
    }

    public void setIdNumberValue(String idNumberValue) {
        this.idNumberValue = idNumberValue;
    }

    public String getUniqueTextValue() {
        return uniqueTextValue;
    }

    public void setUniqueTextValue(String uniqueTextValue) {
        this.uniqueTextValue = uniqueTextValue;
    }

    public String getNameTextValue() {
        return nameTextValue;
    }

    public void setNameTextValue(String nameTextValue) {
        this.nameTextValue = nameTextValue;
    }

    public String getPhoneTextValue() {
        return phoneTextValue;
    }

    public void setPhoneTextValue(String phoneTextValue) {
        this.phoneTextValue = phoneTextValue;
    }

    public String getPhone2TextValue() {
        return phone2TextValue;
    }

    public void setPhone2TextValue(String phone2TextValue) {
        this.phone2TextValue = phone2TextValue;
    }

    public String getAdressTextValue() {
        return adressTextValue;
    }

    public void setAdressTextValue(String adressTextValue) {
        this.adressTextValue = adressTextValue;
    }

    public String getEmailTextValue() {
        return emailTextValue;
    }

    public void setEmailTextValue(String emailTextValue) {
        this.emailTextValue = emailTextValue;
    }

    /**
     * Creates new form MusteriListele
     */
    public MusteriListele() {
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        initComponents();
        this.setLocation(veriIslemleri.StartScreenLocation(this.getBounds().getSize()));
        guncellemeFonksiyonu("SELECT * FROM customerlist");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        customerListTable = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TcSearch = new javax.swing.JTextField();
        nameSearch = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        phoneSearch = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        updateCustomer = new javax.swing.JButton();
        deleteCustomer = new javax.swing.JButton();
        updateCustomerList = new javax.swing.JButton();
        addCustomer1 = new javax.swing.JButton();
        myErrorMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Müşteri Listesi");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        customerListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TC / Vergi No", "İsim (Kişi/Şirket)", "Telefon", "Telefon (Yedek)", "Adres", "E-Mail"
            }
        ));
        customerListTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customerListTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(customerListTable);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("Arama");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("TC/ Verigi No:");

        TcSearch.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        TcSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        TcSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TcSearchActionPerformed(evt);
            }
        });

        nameSearch.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        nameSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameSearchActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("İsim : ");

        phoneSearch.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        phoneSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneSearchActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("Telefon:");

        updateCustomer.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        updateCustomer.setText("Müşteri Güncelle");
        updateCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateCustomerActionPerformed(evt);
            }
        });

        deleteCustomer.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        deleteCustomer.setText("Müşteri Sil");
        deleteCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteCustomerActionPerformed(evt);
            }
        });

        updateCustomerList.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        updateCustomerList.setText("Müşteri Listesi Güncelle");
        updateCustomerList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateCustomerListActionPerformed(evt);
            }
        });

        addCustomer1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        addCustomer1.setText("Müşteri Ekle");
        addCustomer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCustomer1ActionPerformed(evt);
            }
        });

        myErrorMessage.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(myErrorMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(updateCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                                .addComponent(deleteCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                                .addComponent(addCustomer1, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                                .addComponent(updateCustomerList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jScrollPane1))))
                .addGap(16, 16, 16))
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TcSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(phoneSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TcSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(nameSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(phoneSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(updateCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(deleteCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(updateCustomerList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addCustomer1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(myErrorMessage)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deleteCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteCustomerActionPerformed
        int selectedRows = customerListTable.getSelectedRow();
        if (selectedRows == -1) {
            if (customerListTable.getRowCount() == 0) {
                myErrorMessage.setText("Liste Silinecek Kayıt Bulunamadı");
            } else {
                myErrorMessage.setText("Lütfen Silinecek Kayıt Seçiniz");
            }
        } else {
            String sorgu, id;

            sorgu = "DELETE FROM customerlist WHERE Id=" + Integer.valueOf(idNumberValue);

            veriTabaniBaglantisi.sil(sorgu);

            myErrorMessage.setText("Kayıt Başarılı Bir Şekilde Silindi");
            guncellemeFonksiyonu("SELECT * FROM customerlist");
            veriTabaniBaglantisi.close();
        }

    }//GEN-LAST:event_deleteCustomerActionPerformed
    public void guncellemeFonksiyonu(String sorgu) {
        myModel.setRowCount(0);

        ResultSet myRs = veriTabaniBaglantisi.baglanti(sorgu);
        myModel.setColumnIdentifiers(columns);
        try {
            while (myRs.next()) {
                String phoneFormat = myRs.getString("telefon");
                String phone2Format = myRs.getString("telefon2");
                rows[0] = myRs.getString("Id");
                rows[1] = myRs.getString("tc_vergi_no");
                rows[2] = myRs.getString("isim_sirket_kisi");
                rows[3] = veriIslemleri.phoneFormat(phoneFormat);
                rows[4] = veriIslemleri.phoneFormat(phone2Format);
                rows[5] = myRs.getString("adres");
                rows[6] = myRs.getString("email");
                rows[7] = myRs.getString("date");

                myModel.addRow(rows);

            }
        } catch (SQLException ex) {
            Logger.getLogger(MusteriListele.class.getName()).log(Level.SEVERE, null, ex);
        }
        customerListTable.setModel(myModel);

    }
    private void updateCustomerListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateCustomerListActionPerformed
        guncellemeFonksiyonu("SELECT * FROM customerlist");

    }//GEN-LAST:event_updateCustomerListActionPerformed

    private void addCustomer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCustomer1ActionPerformed
        MusteriKayit musteriKayit = new MusteriKayit();
        musteriKayit.setVisible(true);
    }//GEN-LAST:event_addCustomer1ActionPerformed

    private void customerListTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerListTableMouseClicked
        setIdNumberValue((String) myModel.getValueAt(customerListTable.getSelectedRow(), 0));
        setUniqueTextValue((String) myModel.getValueAt(customerListTable.getSelectedRow(), 1));
        setNameTextValue((String) myModel.getValueAt(customerListTable.getSelectedRow(), 2));
        setPhoneTextValue((String) myModel.getValueAt(customerListTable.getSelectedRow(), 3));
        setPhone2TextValue((String) myModel.getValueAt(customerListTable.getSelectedRow(), 4));
        setAdressTextValue((String) myModel.getValueAt(customerListTable.getSelectedRow(), 5));
        setEmailTextValue((String) myModel.getValueAt(customerListTable.getSelectedRow(), 6));
    }//GEN-LAST:event_customerListTableMouseClicked

    private void updateCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateCustomerActionPerformed
        int secim = customerListTable.getSelectedRow();
        if (secim == -1) {
            if (customerListTable.getRowCount() == 0) {
                myErrorMessage.setText("Listenizde Müşteri Bulunmamaktadır");
            } else {
                myErrorMessage.setText("Lütfen Listeden Bir Müşteri Seçiniz");
            }
        } else {
            MusteriGuncelleme musteriGuncelleme = new MusteriGuncelleme(getUniqueTextValue(), getNameTextValue(), getPhoneTextValue(), getPhone2TextValue(), getAdressTextValue(), getEmailTextValue(), getIdNumberValue());
            musteriGuncelleme.setVisible(true);
        }
    }//GEN-LAST:event_updateCustomerActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_formWindowClosing

    private void TcSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TcSearchActionPerformed
        String tc_vergi_no_txt = TcSearch.getText();
        String sorgu = "SELECT * FROM customerlist WHERE tc_vergi_no like '" + tc_vergi_no_txt + "%'";
        guncellemeFonksiyonu(sorgu);

    }//GEN-LAST:event_TcSearchActionPerformed

    private void nameSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameSearchActionPerformed
        String nameSearchTxt = nameSearch.getText();
        String sorgu = "SELECT * FROM customerlist WHERE isim_sirket_kisi like '%" + nameSearchTxt + "%'";
        guncellemeFonksiyonu(sorgu);
    }//GEN-LAST:event_nameSearchActionPerformed

    private void phoneSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneSearchActionPerformed
        String phoneSearchTxt = phoneSearch.getText();
        String sorgu = "SELECT * FROM customerlist WHERE telefon like '" + phoneSearchTxt + "%'";
        guncellemeFonksiyonu(sorgu);
    }//GEN-LAST:event_phoneSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MusteriListele.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MusteriListele.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MusteriListele.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MusteriListele.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MusteriListele().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TcSearch;
    private javax.swing.JButton addCustomer1;
    private javax.swing.JTable customerListTable;
    private javax.swing.JButton deleteCustomer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel myErrorMessage;
    private javax.swing.JTextField nameSearch;
    private javax.swing.JTextField phoneSearch;
    private javax.swing.JButton updateCustomer;
    private javax.swing.JButton updateCustomerList;
    // End of variables declaration//GEN-END:variables
}
