/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.depoyonetim.arayuz;

import com.depoyonetim.islemler.*;
import javax.swing.JFrame;

/**
 *
 * @author ASUS
 */
public class MusteriGuncelleme extends javax.swing.JFrame {
    VeriIslemleri veriIslemleri = new VeriIslemleri();
    String idIntegerValue;

    public MusteriGuncelleme(String uniqueNumberTxt, String nameTxt, String phoneTxt, String phone2Txt, String adressTxt, String emailTxt, String idInteger) {
        initComponents(); // diğer panelden verileri çekmemizi sağlar.
        this.adressTxt.setText(adressTxt);
        this.emailTxt.setText(emailTxt);
        this.nameTxt.setText(nameTxt);
        this.phone2Txt.setText(phone2Txt);
        this.phoneTxt.setText(phoneTxt);
        this.uniqueNumberTxt.setText(uniqueNumberTxt);
        this.idIntegerValue = idInteger;
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);// Bu kod pencereden kapatılırsa sadece bu frame'i kapatır.
        this.setLocation(veriIslemleri.StartScreenLocation(this.getBounds().getSize()));
        this.setResizable(false);
    }

    /**
     * Creates new form MusteriKayit
     */
    public MusteriGuncelleme() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        uniqueNumberText = new javax.swing.JLabel();
        nameText = new javax.swing.JLabel();
        phoneText = new javax.swing.JLabel();
        phone2Text = new javax.swing.JLabel();
        adressText = new javax.swing.JLabel();
        uniqueNumberTxt = new javax.swing.JTextField();
        nameTxt = new javax.swing.JTextField();
        phoneTxt = new javax.swing.JTextField();
        phone2Txt = new javax.swing.JTextField();
        adressTxt = new javax.swing.JTextField();
        emailTxt = new javax.swing.JTextField();
        emailText = new javax.swing.JLabel();
        updateCustomerBtn = new javax.swing.JButton();
        cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Müşteri Güncelle");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        uniqueNumberText.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        uniqueNumberText.setText("TC / Vergi No :");

        nameText.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        nameText.setText("Kişi / Şirket Adı :");

        phoneText.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        phoneText.setText("Telefon :");

        phone2Text.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        phone2Text.setText("Telefon (Yedek) :");

        adressText.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        adressText.setText("Adres :");

        uniqueNumberTxt.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        nameTxt.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        phoneTxt.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        phone2Txt.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        phone2Txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phone2TxtActionPerformed(evt);
            }
        });

        adressTxt.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        emailTxt.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        emailText.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        emailText.setText("E-Mail :");

        updateCustomerBtn.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        updateCustomerBtn.setText("Müşteri Güncelle");
        updateCustomerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateCustomerBtnActionPerformed(evt);
            }
        });

        cancel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cancel.setText("Kapat");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(updateCustomerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(adressTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                            .addComponent(phoneTxt)
                            .addComponent(uniqueNumberTxt)
                            .addComponent(uniqueNumberText)
                            .addComponent(phoneText)
                            .addComponent(adressText))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emailTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                            .addComponent(emailText)
                            .addComponent(phone2Text)
                            .addComponent(nameText)
                            .addComponent(nameTxt)
                            .addComponent(phone2Txt))
                        .addGap(55, 55, 55))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uniqueNumberText)
                    .addComponent(nameText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(phone2Text)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(phone2Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emailText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(uniqueNumberTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(phoneText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(phoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(adressText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(adressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateCustomerBtn)
                    .addComponent(cancel))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void phone2TxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phone2TxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phone2TxtActionPerformed

    private void updateCustomerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateCustomerBtnActionPerformed
        VeriTabaniBaglantisi veriTabaniBaglantisi = new VeriTabaniBaglantisi();
        //

        String uniqeNumber = uniqueNumberTxt.getText();
        String name = nameTxt.getText();
        String phone = phoneTxt.getText();
        String phone2 = phone2Txt.getText();
        String adress = adressTxt.getText();
        String email = emailTxt.getText();
        String sorgu = "UPDATE customerlist SET tc_vergi_no='" + uniqeNumber + "',isim_sirket_kisi='" + name + "',telefon='" + phone + "',"
                + "telefon2='" + phone2 + "',adres='" + adress + "', email='" + email + "' WHERE Id=" + Integer.valueOf(idIntegerValue);
        veriTabaniBaglantisi.guncelle(sorgu);
        //
        //message.setText("Kişi Başarıyla Eklendi");
        //
        uniqueNumberTxt.setText(""); // Bu alanda yazı alanlarının içini güncellemeden sonra boşalttım.
        nameTxt.setText("");
        phoneTxt.setText("");
        phone2Txt.setText("");
        adressTxt.setText("");
        emailTxt.setText("");
    }//GEN-LAST:event_updateCustomerBtnActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        dispose();
    }//GEN-LAST:event_cancelActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        //Boş
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing


    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MusteriGuncelleme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MusteriGuncelleme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MusteriGuncelleme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MusteriGuncelleme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MusteriGuncelleme().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adressText;
    private javax.swing.JTextField adressTxt;
    private javax.swing.JButton cancel;
    private javax.swing.JLabel emailText;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JLabel nameText;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JLabel phone2Text;
    private javax.swing.JTextField phone2Txt;
    private javax.swing.JLabel phoneText;
    private javax.swing.JTextField phoneTxt;
    private javax.swing.JLabel uniqueNumberText;
    private javax.swing.JTextField uniqueNumberTxt;
    private javax.swing.JButton updateCustomerBtn;
    // End of variables declaration//GEN-END:variables

}
