/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.depoyonetim.arayuz;

import com.depoyonetim.islemler.*;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class PersonelBilgisi extends javax.swing.JFrame {

    VeriTabaniBaglantisi veriTabaniBaglantisi = new VeriTabaniBaglantisi();
    VeriIslemleri veriIslemleri = new VeriIslemleri();
    DefaultTableModel employeeModel = new DefaultTableModel();
    Object[] columns = {"Id", "Adı", "Soyadı", "Kullanıcı Adı", "Parola", "Yetki", "Toplam Satış", "Tarih"};
    Object[] rows = new Object[8];
    Object[] dateSearchRows = new Object[8];
    String dataSearchUserName;

    /**
     * Creates new form PersonelBilgisi
     */
    public PersonelBilgisi() {
        initComponents();
        updateEmpoloyeeInformationTable();
        employeeRankings();
        totalSales();
        this.setLocation(veriIslemleri.StartScreenLocation(this.getBounds().getSize()));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        employeeTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        bestEmployeeTextLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        totalMoneyTextLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        bestEmployeeMoneyTextLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        badEmployeeTextLabel = new javax.swing.JLabel();
        badEmployeeMoneyTextLabel = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        authorizationChange = new javax.swing.JButton();
        firstDateDay = new javax.swing.JComboBox<>();
        firstDateMonth = new javax.swing.JComboBox<>();
        firsDateYear = new javax.swing.JComboBox<>();
        secondDateYear = new javax.swing.JComboBox<>();
        secondDateMonth = new javax.swing.JComboBox<>();
        secondDateDay = new javax.swing.JComboBox<>();
        dateControl = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        errorMessage = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Personel Bilgisi");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        employeeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        employeeTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                employeeTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(employeeTable);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("Ayın Personeli :");

        bestEmployeeTextLabel.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        bestEmployeeTextLabel.setForeground(new java.awt.Color(0, 204, 0));
        bestEmployeeTextLabel.setText("Özgür GÜRGEN");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Yaptığı Satış (Aylık) :");

        totalMoneyTextLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        totalMoneyTextLabel.setForeground(new java.awt.Color(51, 204, 0));
        totalMoneyTextLabel.setText("500000 TL");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setText("Toplam Satış :");

        bestEmployeeMoneyTextLabel.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        bestEmployeeMoneyTextLabel.setForeground(new java.awt.Color(0, 204, 0));
        bestEmployeeMoneyTextLabel.setText("30000 TL");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setText("Başarısız Personel :");

        badEmployeeTextLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        badEmployeeTextLabel.setForeground(new java.awt.Color(255, 51, 0));
        badEmployeeTextLabel.setText("Ali GÜMÜŞ");

        badEmployeeMoneyTextLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        badEmployeeMoneyTextLabel.setForeground(new java.awt.Color(255, 51, 0));
        badEmployeeMoneyTextLabel.setText("1000 TL");

        jLabel10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel10.setText("Yaptığı Satış (Aylık) :");

        authorizationChange.setText("Yetki Değiştir");
        authorizationChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                authorizationChangeActionPerformed(evt);
            }
        });

        firstDateDay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        firstDateMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));

        firsDateYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029" }));

        secondDateYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029" }));

        secondDateMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));

        secondDateDay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        dateControl.setText("Tarihler Arası Kontrol");
        dateControl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateControlActionPerformed(evt);
            }
        });

        jLabel2.setText("Gün");

        jLabel4.setText("Ay");

        jLabel6.setText("Yıl");

        errorMessage.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        errorMessage.setForeground(new java.awt.Color(255, 0, 0));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(errorMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bestEmployeeTextLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(badEmployeeTextLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(badEmployeeMoneyTextLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(totalMoneyTextLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bestEmployeeMoneyTextLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(secondDateDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(secondDateMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(secondDateYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(firstDateDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(firstDateMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(firsDateYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(dateControl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(authorizationChange, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(errorMessage))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bestEmployeeTextLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bestEmployeeMoneyTextLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(badEmployeeTextLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(badEmployeeMoneyTextLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totalMoneyTextLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(firstDateDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(firstDateMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(firsDateYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(secondDateDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(secondDateMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(secondDateYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dateControl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(authorizationChange)
                        .addGap(16, 16, 16))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void authorizationChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_authorizationChangeActionPerformed
        String authorization =employeeModel.getValueAt(employeeTable.getSelectedRow(), 5).toString();
        String id = employeeModel.getValueAt(employeeTable.getSelectedRow(), 0).toString();
        if (authorization.equals("Personel")){
            authorization = "Yönetici";
        }
        else{
            authorization = "Personel";
        }
        String sorgu = "UPDATE `users` SET `authorization` = '" + authorization + "' WHERE `users`.`Id` =" +  id;
        veriTabaniBaglantisi.guncelle(sorgu);
        employeeModel.setRowCount(0);
        updateEmpoloyeeInformationTable();
    }//GEN-LAST:event_authorizationChangeActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_formWindowClosing

    private void dateControlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateControlActionPerformed
        employeeModel.setRowCount(0);
        int firstDate = Integer.valueOf(firsDateYear.getSelectedItem().toString() + firstDateMonth.getSelectedItem().toString() + firstDateDay.getSelectedItem().toString());
        int secondDate = Integer.valueOf(secondDateYear.getSelectedItem().toString() + secondDateMonth.getSelectedItem().toString() + secondDateDay.getSelectedItem().toString());
        if (secondDate < firstDate) {
            errorMessage.setText("Lütfen Başlangıç Tarihi Bitiş Tarihinden Küçük Seçin");
            jLabel8.setText("");
            return;
        } else {
            jLabel8.setText(firstDateDay.getSelectedItem().toString() + "/" + firstDateMonth.getSelectedItem().toString() + "/" + firsDateYear.getSelectedItem().toString()
                    + " İle " + secondDateDay.getSelectedItem().toString() + "/" + secondDateMonth.getSelectedItem().toString() + "/" + secondDateYear.getSelectedItem().toString() + " Arası Bilgiler Gösteriliyor");
            String sorgu = "SELECT Id, userName,password, firstName, lastName, authorization, date FROM users" ;
            errorMessage.setText("");
            
            
            ResultSet dateRs = veriTabaniBaglantisi.baglanti(sorgu);
            employeeModel.setColumnIdentifiers(columns);
            try {
                while (dateRs.next()){
                    dateSearchRows[0] = dateRs.getString("Id");
                    dateSearchRows[1] = dateRs.getString("firstName");
                    dateSearchRows[2] = dateRs.getString("lastName");
                    dateSearchRows[3] = dateRs.getString("userName");
                    dateSearchRows[4] = dateRs.getString("password");
                    dateSearchRows[5] = dateRs.getString("authorization");
                    dateSearchRows[6] = veriIslemleri.dateSearchTotalSales(dateRs.getString("userName").toString(), firstDate, secondDate);
                    dateSearchRows[7] = dateRs.getString("date");
                    
                    employeeModel.addRow(dateSearchRows);
                }
            } catch (SQLException ex) {
                ex.printStackTrace();
                System.out.println("hata burada 1");
            }
            employeeTable.setModel(employeeModel);
        }
        employeeRankings();
        totalSales();

    }//GEN-LAST:event_dateControlActionPerformed

    private void employeeTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeeTableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public void totalSales() {
        int sayi = employeeTable.getRowCount();
        double totalSale = 0;
        for (int i = 0; i < sayi; i++) {
            String totalSaleDouble = employeeModel.getValueAt(i, 6).toString();
            totalSale += veriIslemleri.priceReturnFormat(totalSaleDouble);
        }
        totalMoneyTextLabel.setText(veriIslemleri.priceFormat(totalSale) + " TL");
    }

    public void employeeRankings() {
        int rowCount = employeeTable.getRowCount();
        String bestEmployeeString = employeeModel.getValueAt(0, 6).toString();
        double bestEmployee = veriIslemleri.priceReturnFormat(bestEmployeeString) ;
        String bestEmployeeS = employeeModel.getValueAt(0, 1).toString() + " " + employeeModel.getValueAt(0, 2).toString();
        String badEmployeeString = employeeModel.getValueAt(0, 6).toString();
        double badEmployee = veriIslemleri.priceReturnFormat(badEmployeeString);
        String badEmployeeS = employeeModel.getValueAt(0, 1).toString() + " " + employeeModel.getValueAt(0, 2).toString();
        for (int i = 0; i < rowCount; i++) {
            String versusString = employeeModel.getValueAt(i, 6).toString();
            double versus = veriIslemleri.priceReturnFormat(versusString) ;
            String versusS = employeeModel.getValueAt(i, 1).toString() + " " + employeeModel.getValueAt(i, 2).toString();
            if (versus > bestEmployee) {
                bestEmployee = versus;
                bestEmployeeS = versusS;
            }
            if (versus < badEmployee) {
                badEmployee = versus;
                badEmployeeS = versusS;
            }
        }
        bestEmployeeMoneyTextLabel.setText( new DecimalFormat("###,###.##").format(bestEmployee) + " TL");
        bestEmployeeTextLabel.setText(bestEmployeeS);
        badEmployeeTextLabel.setText(badEmployeeS);
        badEmployeeMoneyTextLabel.setText(new DecimalFormat("###,###.##").format(badEmployee) + " TL");
    }

    public void updateEmpoloyeeInformationTable() {
        String sorgu = "SELECT * FROM users";
        ResultSet updateRs = veriTabaniBaglantisi.baglanti(sorgu);
        employeeModel.setColumnIdentifiers(columns);
        try {
            while (updateRs.next()) {
                rows[0] = updateRs.getString("Id");
                rows[1] = updateRs.getString("firstName");
                rows[2] = updateRs.getString("lastName");
                rows[3] = updateRs.getString("userName");
                rows[4] = updateRs.getString("password");
                rows[5] = updateRs.getString("authorization");
                double totalSale = veriIslemleri.totalSales(updateRs.getString("userName"));
                rows[6] = veriIslemleri.priceFormat(totalSale);
                rows[7] = updateRs.getString("date");

                employeeModel.addRow(rows);
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        employeeTable.setModel(employeeModel);
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PersonelBilgisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PersonelBilgisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PersonelBilgisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PersonelBilgisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PersonelBilgisi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton authorizationChange;
    private javax.swing.JLabel badEmployeeMoneyTextLabel;
    private javax.swing.JLabel badEmployeeTextLabel;
    private javax.swing.JLabel bestEmployeeMoneyTextLabel;
    private javax.swing.JLabel bestEmployeeTextLabel;
    private javax.swing.JButton dateControl;
    private javax.swing.JTable employeeTable;
    private javax.swing.JLabel errorMessage;
    private javax.swing.JComboBox<String> firsDateYear;
    private javax.swing.JComboBox<String> firstDateDay;
    private javax.swing.JComboBox<String> firstDateMonth;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> secondDateDay;
    private javax.swing.JComboBox<String> secondDateMonth;
    private javax.swing.JComboBox<String> secondDateYear;
    private javax.swing.JLabel totalMoneyTextLabel;
    // End of variables declaration//GEN-END:variables
}
