/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.depoyonetim.arayuz;

import com.depoyonetim.islemler.*;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class SatisDetay extends javax.swing.JFrame {
    VeriIslemleri veriIslemleri = new VeriIslemleri();
    VeriTabaniBaglantisi veriTabaniBaglantisi = new VeriTabaniBaglantisi();
    DefaultTableModel salesModel = new DefaultTableModel();
    Object[] salesDetailColumn = {"Id", "Barkod No", "Ürün Adı", "Stok Adedi", "Kategori", "Marka", "Alış (TL)", "Satış (TL)", "Raf No", "Alt Raf No", "Müşteri Adı"};
    Object[] salesDetailRow = new Object[11];

    /**
     * Creates new form SatisDetay
     */
    public SatisDetay() {
        initComponents();
        updateSalesDetailTable();
        totalPrice();
        this.setLocation(veriIslemleri.StartScreenLocation(this.getBounds().getSize()));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        salesDetailTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        totalText = new javax.swing.JLabel();
        totalLabel = new javax.swing.JLabel();
        customerNameText = new javax.swing.JLabel();
        customerNameTextField = new javax.swing.JTextField();
        sellerNameText = new javax.swing.JLabel();
        sellerNameTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Satış Detayı");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        salesDetailTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(salesDetailTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 767, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        totalText.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        totalText.setText("Ödenen Tutar :");

        totalLabel.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        totalLabel.setText("0 TL");

        customerNameText.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        customerNameText.setText("Sipariş Sahibi :");

        customerNameTextField.setEditable(false);
        customerNameTextField.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        customerNameTextField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        sellerNameText.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        sellerNameText.setText("Satış Yapan :");

        sellerNameTextField.setEditable(false);
        sellerNameTextField.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(customerNameText)
                    .addComponent(sellerNameText))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totalLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(totalText, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(customerNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sellerNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(customerNameText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(customerNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sellerNameText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sellerNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 174, Short.MAX_VALUE)
                .addComponent(totalText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalLabel)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public void updateSalesDetailTable() {
        String sorgu = "SELECT * FROM saleproducts WHERE CustomerName='" + new SatisListele().sendCustomerName +"' AND Date='" + new SatisListele().sendDate + "'";
        ResultSet detailValueRs = veriTabaniBaglantisi.baglanti(sorgu);
        salesModel.setColumnIdentifiers(salesDetailColumn);
        try {
            while (detailValueRs.next()) {
                double purchasePrice = Double.valueOf(detailValueRs.getString("PurchasePrice"));
                double salePrice = Double.valueOf(detailValueRs.getString("SalePrice"));
                salesDetailRow[0] = detailValueRs.getString("Id");
                salesDetailRow[1] = detailValueRs.getString("BarcodeNo");
                salesDetailRow[2] = detailValueRs.getString("ProductName");
                salesDetailRow[3] = detailValueRs.getString("StockAmount");
                salesDetailRow[4] = detailValueRs.getString("Category");
                salesDetailRow[5] = detailValueRs.getString("Brand");
                salesDetailRow[6] = veriIslemleri.priceFormat(purchasePrice);
                salesDetailRow[7] = veriIslemleri.priceFormat(salePrice);
                salesDetailRow[8] = detailValueRs.getString("ShelfNo");
                salesDetailRow[9] = detailValueRs.getString("BottomShelfNo");
                salesDetailRow[10] = detailValueRs.getString("CustomerName");
                salesModel.addRow(salesDetailRow);
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        salesDetailTable.setModel(salesModel);
        customerNameTextField.setText(new SatisListele().sendCustomerName);
        sellerNameTextField.setText(new SatisListele().sellerName);
    }
    public void totalPrice() {
        if (salesDetailTable.getRowCount() == 0) {
            totalLabel.setText("0 TL");
            return;
        } else {
            String sorgu = "SELECT * FROM saleproducts WHERE CustomerName='" + new SatisListele().sendCustomerName +"' AND Date='" + new SatisListele().sendDate + "'" ;
            ResultSet priceRs = veriTabaniBaglantisi.baglanti(sorgu);
            double totalCartPrice = 0;
            try {
                while (priceRs.next()) {
                    double price = Double.valueOf(priceRs.getString("SalePrice"));
                    int amount = Integer.valueOf(priceRs.getString("StockAmount"));
                    totalCartPrice += (price * amount);
                }

            } catch (SQLException ex) {
                ex.printStackTrace();
            }
            totalLabel.setText(totalCartPrice + " TL");
            //totalPrice = totalCartPrice;
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SatisDetay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SatisDetay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SatisDetay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SatisDetay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SatisDetay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel customerNameText;
    private javax.swing.JTextField customerNameTextField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable salesDetailTable;
    private javax.swing.JLabel sellerNameText;
    private javax.swing.JTextField sellerNameTextField;
    private javax.swing.JLabel totalLabel;
    private javax.swing.JLabel totalText;
    // End of variables declaration//GEN-END:variables
}
